# Generated by Django 3.0.7 on 2021-02-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserStatus', '0002_auto_20210216_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Neutral', 'Neutral'), ('At Capacity', 'At Capacity'), ('Looking For Work', 'Looking For Work')], default='Neutral', max_length=50),
        ),
    ]
